<%@ Page Title="" Language="C#" MasterPageFile="~/admin.Master" AutoEventWireup="true" CodeBehind="CategoriesAdmin.aspx.cs" Inherits="MyAmazon.CategoriesAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="header" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="nav" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="content" runat="server">
    <form runat="server">
        <div style="padding-left:30px">
            <h1>List of Categories</h1><br />
             <asp:GridView ID="Categories" runat="server" DataKeyNames="CategoryID" EnableViewState="false" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="CategoriesEdit" OnRowCancelingEdit="CancelEdit" OnRowUpdating="CategoriesUpdate" style="text-align: center">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                
        </asp:GridView><br /><br />
            <h1>Number of Products in each Category</h1> <br />
            <asp:GridView ID="CategoriesList" runat="server" DataKeyNames="CategoryID" EnableViewState="false" CellPadding="4" ForeColor="#333333" GridLines="None" style="text-align: center">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                
        </asp:GridView><br /><br />
        </div>

        <div style ="padding-left: 30px">
                <h1>Add New Category</h1> <br />
                <p>Category ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <asp:TextBox ID="CID" CssClass="txtbox" runat="server" Width="205px"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="CID" ErrorMessage="Enter Category ID" ForeColor="Red"></asp:RequiredFieldValidator>
                </p>
                <p>&nbsp;</p>
                <p>Category Name&nbsp;&nbsp;&nbsp;&nbsp; <asp:TextBox ID="CName" CssClass="txtbox" runat="server" Width="206px"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="CName" ErrorMessage="Enter a valid Category Name" ForeColor="Red"></asp:RequiredFieldValidator>
                </p>
                <p>&nbsp;</p>
                <p><asp:Button ID="AddCategory" CssClass="btn" runat="server" Text="Add Category" Height="44px" Width="339px" OnClick="AddCategoryOnClick" /></p>
             <br />
            <asp:Label ID="Message" runat="server" CssClass="auto-style10" Text=""></asp:Label>
       
        </div>
    </form>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="footer" runat="server">
</asp:Content>
