<%@ Page Language="C#" MasterPageFile="~/layout.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="MyAmazon.Home" %>

<asp:Content ID="content2" ContentPlaceHolderID="content" runat="server">
    <style type="text/css">
        div {
            font-family: cambria;
            color: antiquewhite;
            text-align: center;
        }

        p {
            font-size: large;
            text-align: center;
            color: antiquewhite;

        }
    </style>


    <form id="form3" runat="server">

        <div>
            <asp:Label ID="Welcome1" runat="server" Text="" Style="font-family: Cambria; font-size: 40px; font-bold: true"></asp:Label>
            <br />
            <asp:Label ID="welcome" runat="server" Text=""></asp:Label>
            <h1>New Arrivals</h1>
            <asp:Label ID="Message" runat="server" Text="Label"></asp:Label></br>
        <asp:GridView ID="newarrivals" runat="server" AutoGenerateEditButton="false"
            AutoGenerateDeleteButton="false" EnableViewState="False" Style="margin: 0px auto" Width="702px"
            BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="None">
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#FAFAE7" />
            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
            <SortedDescendingCellStyle BackColor="#E1DB9C" />
            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        </asp:GridView>
            </br></br>

        <h1>Most Popular</h1>
            <asp:Label ID="Message1" runat="server" Text="Label"></asp:Label></br>
        <asp:GridView ID="Popular" runat="server" AutoGenerateEditButton="false"
            AutoGenerateDeleteButton="False" EnableViewState="False" Style="margin: 0px auto" Width="702px"
            BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="None">
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#FAFAE7" />
            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
            <SortedDescendingCellStyle BackColor="#E1DB9C" />
            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        </asp:GridView>
            </br></br>


        </div>
        <div>

             <h1>Buy Product</h1> <br />
                <p>Product ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <asp:TextBox ID="PID" CssClass="txtbox" runat="server" Width="205px"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="PID" ErrorMessage="Enter valid Product ID to buy" ForeColor="Red"></asp:RequiredFieldValidator>
             </p>
                <p>&nbsp;</p>
                <p>Product Quantity&nbsp;&nbsp;&nbsp;&nbsp; <asp:TextBox ID="PQuant" CssClass="txtbox" runat="server" Width="206px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="PQuant" ErrorMessage="Enter valid Quantity to buy" ForeColor="Red"></asp:RequiredFieldValidator>    
            </p>
                    <p>&nbsp;</p>
                <p><asp:Button ID="BuyProduct" CssClass="btn" runat="server" Text="Buy Product" Height="44px" Width="339px" OnClick="BuyButton_Click" /></p>
             <br />
            <asp:Label ID="MessageBP" runat="server" CssClass="auto-style10" Text=""></asp:Label>
       
        </div>

    </form>
</asp:Content>

