
<%@ Page Title="" Language="C#" MasterPageFile="~/admin.Master" AutoEventWireup="true" CodeBehind="UsersAdmin.aspx.cs" Inherits="MyAmazon.UsersAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="header" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="nav" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="content" runat="server">
    <form id="form1" runat="server">
        <div runat="server" style="padding-left:30px">
        <h1>List of Buyers</h1><br />
            <asp:GridView ID="Buyers" runat="server" EnableViewState="false" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowEditing="BuyersEditing" OnRowCancelingEdit="BuyersCancellingEdit" DataKeyNames="id,email" OnRowUpdating="BuyersUpdate" OnRowDeleting="BuyersDelete" style="text-align: center" Width="817px">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                
            </asp:GridView><br /><br />
            <h1>List of Sellers</h1><br />
            <asp:GridView ID="Sellers" runat="server" EnableViewState="false" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="id,email" OnRowEditing="SellersEditing" OnRowUpdating="SellersUpdate" OnRowCancelingEdit ="SellersCancellingEdit" OnRowDeleting="SellersDelete" style="text-align: center" Width="812px">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView><br /><br />

            <h1>List of Admins</h1><br />
            <asp:GridView ID="Admins" runat="server" EnableViewState="false" CellPadding="4" ForeColor="#333333" GridLines="None" style="text-align: center" Width="805px">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView><br /><br />
            <h1>Add Admin</h1><br />
            <p>
                    <br />
                Full Name*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="FullName" CssClass="txtbox" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="FullName" ErrorMessage="Enter a valid Name" ForeColor="Red"></asp:RequiredFieldValidator>

            </p>
            <br />
            <p>
                Email Address&nbsp;&nbsp;
                <asp:TextBox ID="Email" CssClass="txtbox" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="Email" ErrorMessage="Enter a valid Email ID" ForeColor="Red"></asp:RequiredFieldValidator>
            </p>
            <br />
            <p>
                Password&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
               <asp:TextBox ID="Password" Type="Password" CssClass="txtbox" runat="server" Style="margin-left: 0"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="Password" ErrorMessage="Enter a valid Password" ForeColor="Red"></asp:RequiredFieldValidator>
            </p>
            <br />
            <p>
                &nbsp;Address&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="Address" CssClass="txtbox" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="Address" ErrorMessage="Enter a valid Address" ForeColor="Red"></asp:RequiredFieldValidator>
            </p>
            <br />
            <p>
                City*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="City" CssClass="txtbox" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="City" ErrorMessage="Enter a city" ForeColor="Red"></asp:RequiredFieldValidator>
            </p>
            <br />
            <p>
                Country*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="Country" CssClass="txtbox" runat="server"></asp:TextBox>
                 <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ControlToValidate="Country" ErrorMessage="Enter a country" ForeColor="Red"></asp:RequiredFieldValidator>
            </p>
            <br />
            <p>
                <asp:Button ID="SignupButton" CssClass="btn" runat="server" Text="Add User" Height="44px" Width="339px" OnClick="AddAdmin" />
            </p>
            <br />
            <asp:Label ID="Message" runat="server" CssClass="auto-style10" Text=""></asp:Label>
        </div>
    </form>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="footer" runat="server">
</asp:Content>
